add test for caching, dissect moving parts
kpanic/forecastr pull request #1
Opened 2018-03-26 17:09 UTC by gutschilla

Hi @kpanic ,

I couldn't help myself :grimacing: but had to try that out. Pretty darn cool thing! Would be awesome if you at some point could change `IO.puts` or `IO.write` to some string to append to.

Anyways, if you don't mind too much, I rearranged a few things here and there to break functionality apart so they can be tested. Which I didn't :-)

BTW: The "fix stupidity" commit refers to _my_ stupidity.

Thanks for your kind consideration, 
Martin

2018-03-26 18:45 UTC, kpanic requested changes
Hey @gutschilla ! First of all, thanks for the first PR! :1st_place_medal: 
I left some minor comments :wink: 
much :heart: :green_heart: :yellow_heart: 

Thank you! for your contribution :bow:

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +  @type response :: map()
response is unused

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +    location = query |> String.downcase
Parens :stuck_out_tongue_winking_eye: `String.downcase()`
`String.downcase(query)`

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +    case query |> Forecastr.Cache.get do
`Forecastr.Cache.get(query)`

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +  @spec perform_query(query, when_to_forecast, map()) :: String.t()
`String.t()` shouldn't be:

` {:ok, map()} | {:error, atom()}`

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +  # fetch form cache doesn't take when_to_forecast into account?
Currently no, see TODO note here https://github.com/kpanic/forecastr/pull/1/files#diff-5f151367a5e3a0c573f5f36e29c84d21L25 :point_up:

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +    expiration_minutes = Application.get_env(:forecastr, :ttl, 10 * 60_000)
:+1: for the default argument

2018-03-26 18:45 UTC, kpanic commented on lib/forecastr.ex
> +  @spec forecast(when_to_forecast, String.t(), list()) :: {:ok, map()} | {:error, atom()}
Shouldn't be `:: binary() | {:error, atom()}`? It will be a string returned

2018-03-26 18:46 UTC, kpanic commented
@gutschilla regarding `IO.write` `IO.puts` I would like to keep them in the renderer, because at some point I would like to add the possibility to dynamically select the renderer (think about a json/html/png/etc renderer!)

btw typespecs! Yey! I was too lazy to add them :stuck_out_tongue_winking_eye:

2018-03-27 09:05 UTC, gutschilla commented on lib/forecastr.ex
> +  @spec forecast(when_to_forecast, String.t(), list()) :: {:ok, map()} | {:error, atom()}
As far as I cann see `:ok` will be returned. The strings themselves get IO'ed to STDOUT

2018-03-27 09:08 UTC, gutschilla commented on lib/forecastr.ex
> +  @spec perform_query(query, when_to_forecast, map()) :: String.t()
Very true!

2018-03-27 09:08 UTC, gutschilla commented on lib/forecastr.ex
> +  @type response :: map()
Ah, now it is

2018-03-27 09:08 UTC, gutschilla commented on lib/forecastr.ex
> +    location = query |> String.downcase
A yeah, shouldn't ignore warnings :grimacing: – thanks for pointing me there

2018-03-27 09:09 UTC, gutschilla commented on lib/forecastr.ex
> +    case query |> Forecastr.Cache.get do
It's still the Elixit 0.9-guy in me, I am sorry. Fixed this.

2018-03-27 09:09 UTC, gutschilla commented on lib/forecastr.ex
> +    expiration_minutes = Application.get_env(:forecastr, :ttl, 10 * 60_000)
I wonder, if this is duplicate now when I look at the config

2018-03-27 09:10 UTC, gutschilla commented
@kpanic Thanks for your kind review. I addressed all the issues.

2018-03-27 16:39 UTC, kpanic approved these changes

2018-03-27 16:39 UTC, merged